# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(983, 700)
        MainWindow.setStyleSheet("font: 11pt \"ModeSeven\";\n"
"background-color: rgb(106, 9, 158);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.listWidget = QtWidgets.QListWidget(self.splitter_2)
        self.listWidget.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"FreeMono\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.listWidget.setObjectName("listWidget")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.hexTextEdit = QtWidgets.QTextEdit(self.splitter)
        self.hexTextEdit.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"ModeSeven\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.hexTextEdit.setObjectName("hexTextEdit")
        self.fromHexTextEdit = QtWidgets.QTextEdit(self.splitter)
        self.fromHexTextEdit.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"ModeSeven\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.fromHexTextEdit.setObjectName("fromHexTextEdit")
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("\n"
"font: 75 11pt \"ModeSeven\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);\n"
"background-color: rgb(179, 73, 255);")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"ModeSeven\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"ModeSeven\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.comboBox.setProperty("placeholderText", "")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"ModeSeven\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.comboBox_2.setProperty("placeholderText", "")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 20))
        self.menubar.setStyleSheet("background-color: rgb(23, 2, 35);\n"
"selection-background-color: rgb(65, 5, 98);\n"
"color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDisassembly = QtWidgets.QMenu(self.menubar)
        self.menuDisassembly.setObjectName("menuDisassembly")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionDisassembly = QtWidgets.QAction(MainWindow)
        self.actionDisassembly.setObjectName("actionDisassembly")
        self.menuFile.addAction(self.actionOpen)
        self.menuDisassembly.addAction(self.actionDisassembly)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDisassembly.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JTDisasm"))
        self.groupBox.setTitle(_translate("MainWindow", "config"))
        self.lineEdit.setText(_translate("MainWindow", "400000"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "entry address"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ARCH_X86"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ARCH_ARM"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ARCH_MIPS"))
        self.comboBox.setItemText(3, _translate("MainWindow", "ARCH_PPC"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MODE_64"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "MODE_32"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "MODE_ARM"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "MODE_MIPS_64"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "MODE_MIPS_32"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "MODE_MIPS_32R6"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDisassembly.setTitle(_translate("MainWindow", "Disassembly"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionDisassembly.setText(_translate("MainWindow", "Disassembly"))
        self.actionDisassembly.setShortcut(_translate("MainWindow", "Return"))
