# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'strings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(957, 615)
        Form.setStyleSheet("font: 11pt \"ModeSeven\";\n"
"background-color: rgb(106, 9, 158);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"FreeMono\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 1)
        self.actionGrepStrings = QtWidgets.QAction(Form)
        self.actionGrepStrings.setObjectName("actionGrepStrings")

        self.retranslateUi(Form)
        self.lineEdit.returnPressed.connect(self.actionGrepStrings.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "strings"))
        self.lineEdit.setPlaceholderText(_translate("Form", "grep strings...clear and press <Enter> for get all strings"))
        self.actionGrepStrings.setText(_translate("Form", "grepStrings"))
        self.actionGrepStrings.setShortcut(_translate("Form", "Return"))
