# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syscall_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 728)
        Form.setStyleSheet("font: 11pt \"ModeSeven\";\n"
"background-color: rgb(106, 9, 158);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget86 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget86.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"FreeMono\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.tableWidget86.setObjectName("tableWidget86")
        self.tableWidget86.setColumnCount(0)
        self.tableWidget86.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget86, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget86_64 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget86_64.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"FreeMono\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.tableWidget86_64.setObjectName("tableWidget86_64")
        self.tableWidget86_64.setColumnCount(0)
        self.tableWidget86_64.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget86_64, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidgetarm32 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetarm32.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"FreeMono\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.tableWidgetarm32.setObjectName("tableWidgetarm32")
        self.tableWidgetarm32.setColumnCount(0)
        self.tableWidgetarm32.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetarm32, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidgetarm64 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidgetarm64.setStyleSheet("background-color: rgb(196, 112, 255);\n"
"font: 75 11pt \"FreeMono\";\n"
"border-color: rgb(65, 5, 98);\n"
"selection-color: rgb(65, 5, 98);")
        self.tableWidgetarm64.setObjectName("tableWidgetarm64")
        self.tableWidgetarm64.setColumnCount(0)
        self.tableWidgetarm64.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidgetarm64, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.actionGrepSyscall = QtWidgets.QAction(Form)
        self.actionGrepSyscall.setObjectName("actionGrepSyscall")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Linux System Call Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "x86"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "x86_64"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "arm_32_bit_EABI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "arm64"))
        self.actionGrepSyscall.setText(_translate("Form", "grepSyscall"))
        self.actionGrepSyscall.setShortcut(_translate("Form", "Return"))
